# Generated by Django 4.2.7 on 2023-11-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64, unique=True)),
                ('Password', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.author')),
            ],
        ),
    ]
