# Generated by Django 4.2.7 on 2023-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Title',
            field=models.CharField(default='DefaultTitle', max_length=100),
        ),
    ]
